version: "3"
services:
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    postgresql:
        image: postgres
        restart: always
        volumes:
            - ./postgress-data:/var/lib/postresql/data
        environment:
            - POSTGRES_DB=burgizza
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root

